spring:
  application:
    name: fruitMall
  #####热部署, 修改类和资源时不重启服务
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java  #重启目录
      exclude: static/**  #设置classpath下 static目录内容修改后不重启。一般设置为静态资源目录
    freemarker:
      cache: false  #页面不加载缓存，修改即时生效
  ######数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    云数据库
    url: jdbc:mysql://rm-bp195yd0o28vvx5i5lo.mysql.rds.aliyuncs.com/fruitmall?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useAffectedRows=true&zeroDateTimeBehavior=convertToNull&useOldAliasMetadataBehavior=true
    username: root
    password: Zhaolin0304
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 1
      maximum-pool-size: 3
      auto-commit: true
      idle-timeout: 30000
      pool-name: TutorialsHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  ######文件上传
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
server:
  port: 9090
  ssl:
    key-store: '/home/SSL/6206319_begonia.work.pfx'
    key-store-password: '4GB1v8dg'
mybatis:
  # 设置实体类
  type-aliases-package: glut.fruitmall.model
  mapper-locations: classpath:mapper/*.xml
# 分页
pagehelper:
  helperDialect: mysql
  offsetAsPageNum: true
  rowBoundsWithCount: true
  reasonable: false
  supportMethodsArguments: true
  returnPageInfo: true
  params: count=countSql
wx:
  open:
    app


